### ISSUE TITLE
NullPointerException since micronaut-bom 1.3.2 (micronaut-openapi 1.4.0)

### ISSUE THREAD

**Issue by rdesgroppes** [micronaut-projects/micronaut-openapi#161]
Hi,
Here's what we get when bumping the micronaut-bom version from 1.3.1 to 1.3.2 (micronaut-openapi from 1.3.4 to 1.4.0):
```
> Task :rest:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rest:compileJava'.
> java.lang.NullPointerException

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':rest:compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:205)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:263)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:203)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:184)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:359)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.sun.tools.javac.main.Main.compile(Main.java:553)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:93)
        at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:54)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:39)
        at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkAction.execute(AbstractDaemonCompiler.java:128)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:50)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:47)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:37)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:37)
        at org.gradle.workers.internal.FlatClassLoaderWorker.execute(FlatClassLoaderWorker.java:32)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:84)
        at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:129)
        at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:126)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        ... 3 more
Caused by: java.lang.NullPointerException
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.doBindSchemaAnnotationValue(AbstractOpenApiVisitor.java:757)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.bindSchemaAnnotationValue(AbstractOpenApiVisitor.java:744)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.bindSchemaForElement(AbstractOpenApiVisitor.java:655)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.processSchemaProperty(AbstractOpenApiVisitor.java:625)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.processPropertyElements(AbstractOpenApiVisitor.java:1168)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.populateSchemaProperties(AbstractOpenApiVisitor.java:1154)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.readSchema(AbstractOpenApiVisitor.java:1073)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:940)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.lambda$namesToSchemas$13(AbstractOpenApiVisitor.java:1083)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.namesToSchemas(AbstractOpenApiVisitor.java:1090)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.readSchema(AbstractOpenApiVisitor.java:1061)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:940)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:578)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.processPropertyElements(AbstractOpenApiVisitor.java:1166)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.populateSchemaProperties(AbstractOpenApiVisitor.java:1154)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.readSchema(AbstractOpenApiVisitor.java:1073)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:940)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:585)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.bindSchemaForClassName(AbstractOpenApiVisitor.java:896)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.bindSchemaIfNeccessary(AbstractOpenApiVisitor.java:865)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveAnnotationValues(AbstractOpenApiVisitor.java:480)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.toValueMap(AbstractOpenApiVisitor.java:231)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.annotationValueArrayToSubmap(AbstractOpenApiVisitor.java:825)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.toValueMap(AbstractOpenApiVisitor.java:268)
        at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.toJson(AbstractOpenApiVisitor.java:150)
        at io.micronaut.openapi.visitor.OpenApiControllerVisitor.readApiResponses(OpenApiControllerVisitor.java:562)
        at io.micronaut.openapi.visitor.OpenApiControllerVisitor.lambda$visitMethod$5(OpenApiControllerVisitor.java:169)
        at io.micronaut.openapi.visitor.OpenApiControllerVisitor.visitMethod(OpenApiControllerVisitor.java:132)
        at io.micronaut.annotation.processing.visitor.LoadedVisitor.visit(LoadedVisitor.java:155)
        at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.visitExecutable(TypeElementVisitorProcessor.java:240)
        at com.sun.tools.javac.code.Symbol$MethodSymbol.accept(Symbol.java:1644)
        at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.visitType(TypeElementVisitorProcessor.java:215)
        at com.sun.tools.javac.code.Symbol$ClassSymbol.accept(Symbol.java:1150)
        at io.micronaut.annotation.processing.TypeElementVisitorProcessor.lambda$process$3(TypeElementVisitorProcessor.java:102)
        at io.micronaut.annotation.processing.TypeElementVisitorProcessor.process(TypeElementVisitorProcessor.java:99)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.DynamicProcessor.process(DynamicProcessor.java:52)
        at org.gradle.api.internal.tasks.compile.processing.DelegatingProcessor.process(DelegatingProcessor.java:62)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.access$401(TimeTrackingProcessor.java:37)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:99)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor$5.create(TimeTrackingProcessor.java:96)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.track(TimeTrackingProcessor.java:117)
        at org.gradle.api.internal.tasks.compile.processing.TimeTrackingProcessor.process(TimeTrackingProcessor.java:96)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 25 more
```

**Comment by croudet** [comment]
Can you provide an example that repoduces the problem?

Thanks

**Comment by rdesgroppes** [comment]
@graemerocher sorry for the delay.
Here's indeed what I found:
```java
                    if (!schemaToBind.getEnum().contains(allowableValue)) {
                        schemaToBind.addEnumItemObject(allowableValue);
                    }
```
... where `getEnum` returns `null` for the following schema:
```json
{"allowableValues":["OnRoad"]}
```

`schemaToBind` is:
```java
class StringSchema {
    class Schema {
        type: string
        format: null
        $ref: null
        description: null
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: null
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }
}
```
