### ISSUE TITLE
Warning 'Can't create array of wildcard' with stacktrace when compiling

### ISSUE THREAD

**Issue by loicmathieu** [micronaut-projects/micronaut-openapi#1618]
### Expected Behavior

No warning is displayed

### Actual Behaviour

There is a warning `Can't create array of wildcard` with a big stacktrace when compiling a Micronaut application.

```
warning: Error with getting properties for class java.lang.Class: java.lang.UnsupportedOperationException: Can't create array of wildcard
  Can't create array of wildcard
> Task :webserver:compileJava
  java.lang.UnsupportedOperationException: Can't create array of wildcard
  	at io.micronaut.annotation.processing.visitor.JavaWildcardElement.withArrayDimensions(JavaWildcardElement.java:125)
  	at io.micronaut.inject.ast.ArrayableClassElement.toArray(ArrayableClassElement.java:27)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:282)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:213)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:191)
  	at io.micronaut.annotation.processing.visitor.JavaMethodElement.returnType(JavaMethodElement.java:340)
  	at io.micronaut.annotation.processing.visitor.JavaMethodElement.getGenericReturnType(JavaMethodElement.java:210)
  	at io.micronaut.inject.ast.utils.AstBeanPropertiesUtils.processGetter(AstBeanPropertiesUtils.java:244)
  	at io.micronaut.inject.ast.utils.AstBeanPropertiesUtils.resolveBeanProperties(AstBeanPropertiesUtils.java:105)
  	at io.micronaut.annotation.processing.visitor.JavaClassElement.getBeanProperties(JavaClassElement.java:343)
  	at io.micronaut.annotation.processing.visitor.JavaClassElement.getBeanProperties(JavaClassElement.java:298)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.populateSchemaProperties(AbstractOpenApiVisitor.java:2455)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:1966)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:983)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:927)
```

Complete stacktrace: 
[warning-micronaut-compile.txt](https://github.com/micronaut-projects/micronaut-core/files/14634954/warning-micronaut-compile.txt)

### Version

4.3.4

**Comment by altro3** [comment]
@graemerocher Why you move this bug to `micronaut-openapi`? This is bug in core module. Looke to logs:
```
warning: Error with getting properties for class java.lang.Class: java.lang.UnsupportedOperationException: Can't create array of wildcard
  Can't create array of wildcard
  java.lang.UnsupportedOperationException: Can't create array of wildcard
  	at io.micronaut.annotation.processing.visitor.JavaWildcardElement.withArrayDimensions(JavaWildcardElement.java:128)
  	at io.micronaut.inject.ast.ArrayableClassElement.toArray(ArrayableClassElement.java:27)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:282)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:213)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:191)
  	at io.micronaut.annotation.processing.visitor.JavaMethodElement.returnType(JavaMethodElement.java:342)
  	at io.micronaut.annotation.processing.visitor.JavaMethodElement.getGenericReturnType(JavaMethodElement.java:212)
  	at io.micronaut.inject.ast.utils.AstBeanPropertiesUtils.processGetter(AstBeanPropertiesUtils.java:244)
  	at io.micronaut.inject.ast.utils.AstBeanPropertiesUtils.resolveBeanProperties(AstBeanPropertiesUtils.java:105)
  	at io.micronaut.annotation.processing.visitor.JavaClassElement.getBeanProperties(JavaClassElement.java:346)
  	at io.micronaut.annotation.processing.visitor.JavaClassElement.getBeanProperties(JavaClassElement.java:301)
  	at io.micronaut.openapi.visitor.SchemaDefinitionUtils.populateSchemaProperties(SchemaDefinitionUtils.java:1488)
```

This exception throws when `micronaut-inject` introspecting class `java.lang.Class`. 

I don't understand, why somebody want to return `java.lang.Class` structure in DTO, but problem only with introspection, not in `micronaut-openapi`.

I believe, the problem is here:

1. AbstractJavaElement

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/2aa11fcd-473a-4da6-927a-ef080a960d41)

2. JavaWildcardElement

![изображение](https://github.com/micronaut-projects/micronaut-openapi/assets/48474279/c4df27f3-2fa8-4617-8529-5110ad62be3f)

Need to move this isssue back and solve the problem with wildcard arrays

@dstepanov

**Comment by graemerocher** [comment]
the openapi module shouldn't be traversing into `java.lang.Class` and should fail compilation

**Comment by altro3** [comment]
Why? In example I see this classes structure:

```java
public class BulkErrorResponse {
    String message;
    Set<ManualConstraintViolation<String>> invalids;

    public String getMessage() {
        return message;
    }

    public Set<ManualConstraintViolation<String>> getInvalids() {
        return invalids;
    }
}
```

From this DTO we try to introspect class `ManualConstraintViolation<String>` for property `invalids`, and next see to the `ManualConstraintViolation` class structure:

```java
public class ManualConstraintViolation<T> implements ConstraintViolation<T> {
....
    @Override
    public Class<T> getRootBeanClass() {
        return null;
    }
...
}
```

And that's why we're trying to introspect `java.lang.Class`. But I don't see any problem to introspect this class and in my opinion current exception is a bug in core.

Also, you need to understand. The problem in method `ClassElement.getBeanProperties()`. Exception throws wehn I try to process `ManualConstraintViolation` class. On that moment, I don't know anything about properties of this class and I don't know anything about `java.lang.Class`. Exception throws BEFORE  I start iterate properties in `ManualConstraintViolation` class element. I can't skip `java.lang.Class` classelemtn, because core module trying introspect it!!! Not micronaut-openapi!

Again: this is a bug in core module
